name: Deps Install
description: Install node_modules deps for jobs

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
       # cache: "yarn"   
        
    - name: Yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "::set-output name=dir::$(yarn cache dir)"     
        
    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          ${{ steps.yarn-cache-dir-path.outputs.dir }}        
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-node-modules-      
        
    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: yarn install --frozen-lockfile
          
