name: recoil-spring CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: node install
        uses: ./.github/actions/node-install

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: install
    steps:
     - name: Checkout branch
       uses: actions/checkout@v3
     - name: node install
       uses: ./.github/actions/node-install
     - run: yarn lint:nocache

  types:
    name: Check TS types
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: node install
        uses: ./.github/actions/node-install
      - run: yarn ts:test
