# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: recoil-spring CI

on:
  push:
    #branches: [ "master" ]
  pull_request:
    #branches: [ "master" ]

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        uses: bahmutov/npm-install@v1

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: install
    steps:
     - run: yarn lint    
     
  types:
    name: Check TS types
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: yarn types
    
#   build-and-test:
#     runs-on: ubuntu-latest
#     name: Test & Build Recoil:Spring
#    steps:
 #     - uses: actions/checkout@v3
  #    - uses: bahmutov/npm-install@v1
   #   - run: npm t

#     strategy:
#      matrix:
#         node-version: [16.x]
        # node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:    
#     - uses: actions/checkout@v3    
#     - uses: bahmutov/npm-install@v1
    #- name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v3
    #  with:
    #    node-version: ${{ matrix.node-version }}
    #    cache: 'yarn'
#     - run: yarn lint    
    #- run: npm ci
    #- run: npm run build --if-present
    #- run: npm test
